#!/bin/sh
echo "Requesting root privlidges for installs."
[ "$UID" -eq 0] || exec sudo "$0" "$@"

OS=$(echo $1 | tr '[:upper:]' '[:lower:]')

if [ "$OS" = 'unix' ]; then
    cmake_type="Unix Makefiles"
else if [ "$OS" = 'linux' ]; then
    cmake_type="Unix Makefiles"
else if [ "$OS" = 'osx' ]; then
    cmake_type="Unix Makefiles"
else if [ "$OS" = 'windows' ]; then
    cmake_Type="MinGW Makefiles"
else if [ "$OS" = 'vs15' ]; then
    cmake_type='Visual Studio 15 2017 Win64'
else if [ "$OS" = 'vs14' ]; then
    cmake_type='Visual Studio 14 2015 Win64'
else if [ "$OS" = 'help' || "$Os" = '' ]; then
    echo "Setup Options: \n Unix, Linux, OSX, Windows (MinGW), VS15, VS14."
    exit 1
fi

echo "Starting setup. \n Building Dependencies."
cd dep
echo "Cloning OpenAL Soft"
git clone https://github.com/kcat/openal-soft
cd openal-soft
git checkout 6761218e51699f46bf25c377e65b3e9ea5e434b9
echo "Building OpenAL-Soft"
cmake -G "Unix Makefiles"
make
sudo make install

cd ..
echo "Cloning GLFW"
git clone https://github.com/glfw/glfw
cd glfw
git checkout b0796109629931b6fa6e449c15a177845256a407
echo "Building GLFW."
cmake -G "Unix Makefiles"
make
sudo make install

cd ..
echo "Cloning MiniZ"
git clone https://github.com/richgel999/miniz
cd miniz
git checkout a4264837ae37384b1d7a205a6732db322f0f3769
echo "Building miniz"
cmake -G "Unix Makefiles"
make
sudo make install
cd ../..
make
