#!/bin/sh

OS=$(echo $1 | tr '[:upper:]' '[:lower:]')

if [ "$OS" = 'unix' ]; then
	type="Unix Makefiles"
elif [ "$OS" = 'mingw' ]; then
	type="MinGW Makefiles"
elif [ "$OS" = 'vs15' ]; then
	type="Visual Studio 15 2017 Win64"
elif [ "$OS" = 'vs14' ]; then
	type="Visual Studio 14 2015 Win64"
else
	type="Unix Makefiles"
fi

echo "Starting setup & Building Dependencies."
echo "Using: $type"
cd dep
echo "Cloning OpenAL Soft"
git clone https://github.com/kcat/openal-soft
cd openal-soft
git checkout 6761218e51699f46bf25c377e65b3e9ea5e434b9
echo "Building OpenAL-Soft"
cmake -G "$type" 
make
sudo make install

cd ..
echo "Cloning GLFW"
git clone https://github.com/glfw/glfw
cd glfw
git checkout b0796109629931b6fa6e449c15a177845256a407
echo "Building GLFW."
cmake -G "$type"
make
sudo make install
