#!/bin/sh

echo "Starting setup & Building Dependencies."
cd dep/openal-soft
echo "Building OpenAL Soft"
cmake -G "Unix Makefiles" 
make

cd ../glfw
echo "Building GLFW."
cmake -G "Unix Makefiles"
make

cd ../..
make
