name: Build Astera
on: push

jobs:
  build:
    name: Build Astera
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      CMAKE_GENERATOR: Ninja
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install CMake and Ninja
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade cmake ninja
      - name: Install Ubuntu Dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y mesa-common-dev xorg-dev libgl-dev libopenal-dev
      - name: Install Mac Dependencies
        if: contains(matrix.os, 'mac')
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew update
          brew install pkg-config
          brew install openal-soft
          echo 'export PATH="/usr/local/opt/openal-soft/bin:$PATH"' >> /Users/runner/.bash_profile
          export PKG_CONFIG_PATH="/usr/local/opt/openal-soft/lib/pkgconfig"
      - name: Configure
        run: >-
          cmake -Bbuild -S${{ github.workspace }} 
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} 
      - name: Build
        run: cmake --build build
